# Generated by Django 4.2.1 on 2023-06-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
