# Generated by Django 4.2.1 on 2023-05-31 22:18

import discordauth.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=255)),
                ('global_name', models.CharField(blank=True, max_length=64, null=True)),
                ('avatar', models.CharField(max_length=32)),
                ('discriminator', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', discordauth.managers.CustomUserManager()),
            ],
        ),
    ]
