# Generated by Django 4.2.1 on 2023-06-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordauth', '0002_user_admin_username_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
